### ISSUE TITLE
Client.post: error message on success

### ISSUE THREAD

**Issue by evilfer** [funpdbe-consortium/funpdbe-client#3]
Hi, 
I'm getting this log on a successful post:

```
INFO:client:POST None to cansar (overwrite=True)
ERROR:client:No file path to JSON(s) specified
INFO:client:JSON complies with FunPDBe schema
INFO:client:[201] SUCCESS
```

What does the ERROR mean?

**Comment by mvaradi** [comment]
This was fixed earlier I think - it was trying to find the path to the JSON as an input parameter, which was not needed when used as a plugin.
