### ISSUE TITLE
Post return value misses error

### ISSUE THREAD

**Issue by evilfer** [funpdbe-consortium/funpdbe-client#4]
https://github.com/funpdbe-consortium/funpdbe-client/blob/ab5b697833aed67a204bd1f4b5315b98da17cb3f/funpdbe_client/plugin.py#L74-L75

Those two lines hide the different responses from client.py, and make it very difficult to check whether the plugin.post request was successful or not. It would be useful if client.post returned different values on success/failure.

**Comment by mvaradi** [comment]
Additionally, if you try to catch errors when there is an actual response, the client.post call returns the reponse with .status_code which can be checked
