### ISSUE TITLE
User name and passwords should not be needed

### ISSUE THREAD

**Issue by skodapetr** [funpdbe-consortium/funpdbe-client#5]
The readme file states that: 
```With the exception of GET calls, all other calls require user authentication.```
however with command: 
```python funpdbe_client.py --mode=get --resource=14-3-3-pred```
the user is still prompted for the username and password. 

Manual curl on URL (that the script try to access) returns some data. 

I believe this is issue with implementation. 

If the GET on data should truly require login there should be a link or some comment on how to register.
If there should be requirement to register that would IMHO discourage many potential users.

**Comment by mvaradi** [comment]
Again, this is not accessing the production database, i.e. this client should not be used for trying to retrieve data. Registration is required for all the depositors, as is also a formal agreement between PDBe and the depositor. The general public is not intended to use the client - as mentioned in issue #7 the GET calls are only for checking if the data went through, not for getting the complete data back
